name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qa:
    name: Code QA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Formatting & linting
        run: npm run ci

      - name: Type checking
        run: npm run typecheck

      - name: Run tests
        run: npm run test
